version: '3.5'
services:
  form_front:
    container_name: front_distribuidos
    build:
        context: .
        dockerfile: Dockerfile
    command: bash -c "npm install && npm run serve"
    environment:
      -  VUE_APP_SECRET_KEY=vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
    volumes:
        - .:/app
    ports:
        - "8080:8080"

volumes:
    nodemodules: